export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_KANJIS_PENDING = 'REQUEST_KANJIS_PENDING';
export const REQUEST_KANJIS_SUCCESS = 'REQUEST_KANJIS_SUCCESS';
export const REQUEST_KANJIS_FAILED = 'REQUEST_KANJIS_FAILED';
