export const CHANGE_SEARCH_FIELD: string = 'CHANGE_SEARCH_FIELD';

export const REQUEST_KANJIS_PENDING: string = 'REQUEST_KANJIS_PENDING';
export const REQUEST_KANJIS_SUCCESS: string = 'REQUEST_KANJIS_SUCCESS';
export const REQUEST_KANJIS_FAILED: string = 'REQUEST_KANJIS_FAILED';
